### ISSUE TITLE
Scene V1.0

### ISSUE THREAD

**Issue by 54UL** [54UL/80CC#2]
# TODO:
- [ ] Implement removable nodes and components
- [x] Lineal Scene processing (BASE SCENE API)
- [x] #8 
- [x] #10 
- [x] #6
- [x] #20 
- [ ] Implement memory movable nodes and components (check parenting behaviors)

## BACKLOG FOR 2.0V
- [ ] Spatial Partitioning(QUAD TREE)
- [ ] Frustum Culling
- [ ] Occlusion Culling
- [ ] Batching and Instancing
- [ ] Asynchronous Loading(with cache sytem for loading and unloading of resources on the fly)
- [ ] GPU Compute Shaders (if i have find usefull to compute something in the gpu)
